routes/web.php
            Route::post('/add', 'ManageAdsController@bannerAdd')->name('add.banner.post');
            Route::get('/banner/edit/{id}', 'ManageAdsController@bannerEdit')->name('banner.edit');
            Route::post('/banner/{id}', 'ManageAdsController@bannerUpdate')->name('banner.update');

            // Edit
            // Update
            // Delete
            Route::delete('/del/{id}', 'ManageAdsController@bannerDelete')->name('banner.delete');
        });
            //banner stats
            Route::get('/advertisement-stats', 'ManageAdsController@adsReport')->name('ad.report');

        });

    });

//    ----------------------------------------------- Auth Routes ------------------------------------------------------

    // Password Reset Routes...
    Route::get('/password/reset/auth', 'Auth\ForgotPasswordController@showlinkrequestform')->name('auth.password.reset');
    Route::post('password/email', 'auth\forgotpasswordcontroller@sendresetlinkemail')->name('auth.password.reset');
    Route::get('password/resets/{token}', 'auth\resetpasswordcontroller@showresetform2')->name('password.resets');

    // Auth
    Route::get('/login','LoginController@index')->name('login');
    Route::get('/register', "RegisterController@index")->name('register');
    Route::get('/{level}/{userid}/register/{custom}', "RegisterController@registerByInvite");
    Route::get('/verification','LoginController@check')->name('login.check');
    Route::get('/userlogout', 'LoginController@user_logout')->name('userlogout');
    Route::post('/login/checkemail','LoginController@checkemail')->name('login.checkemail');
    Route::post('/login/checkuserlink','LoginController@checkuserlink')->name('login.checkuserlink');
    Route::post('/login/checkmobile','LoginController@checkmobile')->name('login.checkmobile');
    Route::post('/userprofile/store','RegisterController@store')->name('register.store');
    Route::post('/register/verify}','RegisterController@verify')->name('register.verify');

//    ----------------------------------------------- Social Site Routes -----------------------------------------------

    Auth::routes();
    Route::group(['middleware' => ['auth'], 'prefix' => '', 'as' => 'user.'], function ()
    {
        Route::get('/', 'HomeController@myopinion')->name('news');
        Route::get('/{link}', 'HomeController@index')->name('home');
        Route::get('/userprofiles/user', 'HomeController@search')->name('search');

        Route::get('/ads/click/{adID}', 'HomeController@adClicked')->name('adClicked');
        Route::get('/chat/user', 'HomeController@chatSystem')->name('chatSystem');
        Route::post('/chat/upload-attachment', 'HomeController@uploadChatAttachment')->name('uploadChatAttachment');
        Route::post('/chat/groups/upload', 'HomeController@uploadGroupAttachment')->name('uploadGroupAttachment');

        // Route for new Chat
        Route::get('/newchat/user', 'HomeController@newChatSystem')->name('newChatSystem');

        // Route Resource for User
        // Route::resource('users', 'Admin\UsersController');

        // Route for User Profile
        Route::get('/profiles/user', ['uses' => 'Admin\UserProfileController@profiles', 'as' => 'profiles']);
        Route::get('/request/user', ['uses' => 'Admin\FriendsController@requestindex', 'as' => 'request']);
        Route::post('/invites/user', ['uses' => 'Admin\InvitesController@invites', 'as' => 'invites']);
        Route::get('/re_invites/user', ['uses' => 'Admin\InvitesController@reInvites', 'as' => 're_invites']);
        Route::post('/updateInvite/user', ['uses' => 'Admin\InvitesController@updateInvite', 'as' => 'updateInvite']);
        Route::get('/{id}', ['uses' => 'Admin\UserProfileController@individualprofile', 'as' => 'individualprofile']);

        Route::get('/bio/user', ['uses' => 'Admin\UserProfileController@bioindex', 'as' => 'bio']);
        Route::post('/bio/store', ['uses' => 'Admin\UpdateController@bioupdate', 'as' => 'bio.store']);
        Route::put('/about/update', ['uses' => 'Admin\UpdateController@aboutupdate', 'as' => 'about.update']);
        Route::post('/tab-update/{id}', ['uses' =>'Admin\UpdateController@tabupdate', 'as' => 'tab.update']);
        Route::get('/weburl/user/{id}', ['uses' => 'Admin\UserProfileController@weburlmodal', 'as' => 'weblink']);
        Route::get('/weburl/edit/{id}', ['uses' => 'Admin\UserProfileController@editurl', 'as' => 'weburl']);
        Route::post('/weburl/edit', ['uses' => 'Admin\UpdateController@editurlupdate', 'as' => 'weburl']);
      //feedback user routes
      Route::get('/user/feedback',['uses' => 'Admin\FeedBackController@userfeedback', 'as' => 'feedback']);
      Route::post('/feedback/uploadimages',['uses' =>'Admin\FeedBackController@uploadimages', 'as' => 'feedback.uploadimages']);
      Route::post('/feed/store',['uses' =>'Admin\FeedBackController@store', 'as' => 'feed.store']);
      Route::post('/feed/deleteimages',['uses' =>'Admin\FeedBackController@deleteimages', 'as' => 'feed.deleteimages']);
        //  Route for Friends
        Route::get('/friendsdata/list', ['uses' => 'Admin\FriendsController@friendList', 'as' => 'friendsListing']);
        Route::get('/users/list', ['uses' => 'Admin\FriendsController@userList', 'as' => 'usersListing']);
        Route::get('/friend/{id}', ['uses' => 'Admin\FriendsController@addfriends', 'as' => 'friend']);
        Route::get('/unfriend/{id}', ['uses' => 'Admin\FriendsController@unfriend', 'as' => 'unfriend']);
        Route::post('/friend/acceptrequest','Admin\FriendsController@acceptrequest')->name('acceptrequest');
        Route::post('/friend/rejectrequest','Admin\FriendsController@rejectrequest')->name('rejectrequest');
        Route::get('/cancelrequest/{id}','Admin\FriendsController@cancelrequest')->name('cancelrequest');
        Route::get('/confirmrequest/{id}','Admin\FriendsController@confirmrequest')->name('confirmrequest');
        Route::get('/ignorerequest/{id}','Admin\FriendsController@ignorerequest')->name('ignorerequest');
        Route::get('/friends/{id}', ['uses' => 'Admin\FriendsController@viewfriends', 'as' => 'friends']);

        // Route for Followers
        Route::get('/follow/{id}', ['uses' => 'Admin\FollowersController@addfollowers', 'as' => 'follow']);
        Route::get('/unfollow/{id}', ['uses' => 'Admin\FollowersController@removefollowers', 'as' => 'unfollow']);
        Route::get('/followers/{id}', ['uses' => 'Admin\FollowersController@viewfollowers', 'as' => 'followers']);
        Route::get('/following/{id}', ['uses' => 'Admin\FollowersController@viewfollowing', 'as' => 'following']);

        // Route for Notifications
        Route::get('/notification/user', ['uses' => 'NotificationController@view', 'as' => 'notification.view']);
        Route::post('/notification/read', ['uses' => 'NotificationController@read', 'as' => 'notification.read']);
        Route::post('/notification/checked', ['uses' => 'NotificationController@checked', 'as' => 'notification.checked']);
        Route::post('/sms/messageCheck', ['uses' => 'Admin\InvitesController@messageCheck', 'as' => 'sms.messageCheck']);
        Route::post('/sms/messagesChecked', ['uses' => 'Admin\InvitesController@messagesChecked', 'as' => 'sms.messagesChecked']);
        Route::post('/sms/sendSMS', ['uses' => 'Admin\InvitesController@sendSMS', 'as' => 'sms.sendSMS']);
        Route::post('/sms/updateSMSNotification', ['uses' => 'Admin\InvitesController@updateSMSNotification', 'as' => 'sms.updateSMSNotification']);


        // Route for Posts
        Route::post('/post/store','Admin\PostController@store')->name('post.store');
        Route::post('/post/delete/','Admin\PostController@delete')->name('post.delete');
        Route::post('/post/edit','Admin\PostController@edit')->name('post.edit');
        Route::post('/post/fetch','Admin\PostController@fetchdata')->name('post.fetchdata');
        Route::post('/post/expert','Admin\PostController@expertdata')->name('post.expertdata');
        Route::post('/post/uploadimages','Admin\PostController@uploadimages')->name('post.uploadimages');
        Route::post('/post/deleteimages','Admin\PostController@deleteimages')->name('post.deleteimages');
        Route::post('/post/clearimages','Admin\PostController@clearimages')->name('post.clearimages');
        Route::get('/post/single/{id}','Admin\PostController@singlepost')->name('single.post');
        Route::get('/post/all','HomeController@allexperts')->name('allexperts.post');

        // Update cover photo
        Route::get('/cover-photo/user', ['uses' => 'Admin\UserProfileController@coverindex', 'as' => 'cover']);
        Route::post('/coverphoto/update', ['uses' => 'Admin\UpdateController@coverupdate', 'as' => 'cover.update']);
        Route::post('/coverphoto/remove', ['uses' => 'Admin\UpdateController@coverremove', 'as' => 'cover.remove']);

        //payment routes
        Route::get('payment', ['uses' => 'PaymentController@index', 'as' => 'payment']);
        Route::post('charge', ['uses' => 'PaymentController@charge', 'as' => 'charge']);
        // Update Profile Photo
        Route::post('/profilephoto/update', ['uses' => 'Admin\UpdateController@profileupdate', 'as' => 'profile.update']);

        // Update Profile Link
        Route::post('/profilelink/update', ['uses' => 'Admin\UpdateController@profilelink', 'as' => 'profilelink.update']);


//      // Sports Update
        Route::post('/sport/update', ['uses' => 'Admin\UpdateController@sportupdate', 'as' => 'sport.update']);

        Route::post('/save-token/user', [App\Http\Controllers\NotificationController::class, 'saveToken'])->name('save-token');
        Route::get('/desktop/notification', [App\Http\Controllers\NotificationController::class, 'index']);
        Route::get('/send-notification/user', [App\Http\Controllers\NotificationController::class, 'sendNotification'])->name('send.notification');
    });

app/Models/Admin/Sport.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sport extends Model
{
    use SoftDeletes;
    protected $fillable = ['id',
        'name',
        'type',
        'status',
        'created_by','updated_by','deleted_by'
    ];
    protected $table = 'sports';
}

resources/views/sports/coverphoto.blade.php
<div class="add-pic-box">
    <div class="container">
        <div class="row no-gutters">
            <div class="cover-photo">
                <button onclick="addRemoveCoverPhoto()" class="dropdown-open"><i class="fa fa-camera"></i>Edit Cover Photo</button>
                <div id="dropdown-content" class="add-remove-cover-photo">
                    {!! Form::model($userprofile, ['method' => 'POST','id'=>'coverForm', 'route' => ['user.cover.update', $userprofile->id], 'data-parsley-validate','files'=>'true','enctype'=>'multipart/form-data']) !!}
                        <div class="upload-btn-wrappers upload-cover-photo">
                            <a class="upload-photo"><i class="fa fa-upload mr-2"></i>Upload Cover Photo</a>
                            {!! Form::file('coverphoto', [
                               'onchange'=>'coverpicURL(this,"cover_photo")','accept'=>'image/*','id'=>'coverphoto'
                            ]) !!}
                            @if($errors->has('coverphoto'))
                                <span class="help-block">
                                    {{ $errors->first('coverphoto') }}
                                </span>
                            @endif
                        </div>
                    {!! Form::close() !!}
    @if($userprofile['coverphoto']=='yes')
        <a class="remove-photo" onclick="removecoverphoto()"><i class="fa fa-trash mr-2"></i>Remove Cover Photo</a>
    @endif
</div>
</div>
</div>
</div>
</div>
@include('sports.js.cover')

resources/views/sports/expertposts.blade.php
<!DOCTYPE html>
<html>

@include('sports.head')
<body class="main-body">
<div class="wrapper">
    @include('sports.head_main')
    <main>
        <div class="container">
        </div>
        <div class="main-section">
            <div class="container-fluid no-pdd">
                <div class="main-section-data">
                    <div class="row">
                        <div class="col-lg-3 col-md-2 col-sm-12 col-12 no-pdd">
                            {{--<div class="suggestions full-width">--}}
                                {{--<div class="sd-title text-center">--}}
                                    {{--<h3>Add or invite friends</h3>--}}
                                {{--</div>--}}
                                {{--<div class="suggestions-list">--}}
                                    {{--<div class="view-more">--}}
                                        {{--<div class="user_pro_status">--}}
                                            {{--<ul class="flw-hr">--}}
                                                {{--<li><a href="{{ route('user.profiles') }}" title="" class="add-friends">Add Friends</a></li>--}}
                                            {{--</ul>--}}
                                            {{--<ul class="flw-hr">--}}
                                                {{--<li><a class="invites-friends" title="" data-toggle="modal" data-target="#invites"  onclick="via_invites()">Invite Friends</a></li>--}}
                                            {{--</ul>--}}
                                        {{--</div>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                        </div>
                        <div class="col-lg-6 col-md-8 col-sm-12 col-12 no-pdd">
                            <div>
                                @if(Session::get('success'))
                                    <div id="mydiv">
                                        <div  class="alert alert-success alert-dismissible fade show" role="alert">
                                            <p>{{Session::get('success')}}</p>
                                        </div>
                                    </div>
                                @endif
                            </div>
                            <div class="post-topbar">
                         <h1 class="open-post-popup col-lg-12 col-md-12 col-sm-12 text-center" style="font-weight:bolder !important; color:black !important; left:0 !important; top: 0!important;" title="" >Specialists</h1>
                                  
                            </div>


                            @if(count($posts)>0)
                                <div class="main-ws-sec">
                                    <div class="posts-section" id="post-data">
                                        @include('sports.lists.allexpert')
                                    </div>
                                </div>
                            @else
                                <div class="main-ws-sec">
                                    <div class="posts-section">
                                        <div class="post-bar">
                                            <div class="post_topbar">
                                            </div>
                                            <div class="epi-sec">
                                                <div class="job_descp">
                                                    <p>No Post Yet.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            <div class="ajax-load text-center d-none">
                                <div class="process-comm">
                                    <div class="spinner">
                                    <div class="bounce1"></div>
                                    <div class="bounce2"></div>
                                    <div class="bounce3"></div>
                                    </div>
                                    <br/>
                                    <br/>
                                </div>
                            </div>
                            <br/>
                        </div>
                        <div class="col-lg-3 col-md-2 col-sm-12 col-12 no-pdd">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Contact List -->
    @include('sports.contact')

    <!-- Post Modal -->
    @include('sports.modal.addpost')

    <!-- Update Modal -->
    @include('sports.modal.editpost')

    <!-- Invites Modal -->
    @include('sports.modal.invites')
</div>
@include('sports.script')
@include('sports.js.post')
@include('sports.js.invites')
@include('sports.js.images')
</body>
</html>

resources/views/sports/head_main.blade.php
@php
    $userprofile = \App\Models\Admin\UserProfile::select('user_profiles.*','users.user_link as user_link')
            ->join('users', 'users.id', '=', 'user_profiles.user_id')
            ->where('user_profiles.user_id',Auth::user()->id)->first();
    $userprofileall = \App\Models\Admin\UserProfile::take(10)->get();
    $userNotifications = \App\Models\Admin\UserNotification::orderBy('created_at','desc')->where('user_id',Auth::user()->id)->take(20)->get();
    $count = \App\Models\Admin\UserNotification::where('user_id',Auth::user()->id)->sum('checked');

@endphp
<style>
    input::-webkit-calendar-picker-indicator {
display: none !important;
}
</style>
<header>
    
    <div class="container-fluid">
        <div class="header-data">
            <div class="logo">
                <a href="{{route('user.chatSystem')}}" title=""><img src="{{ asset('public/sports/images/login images') }}/logo.svg" alt=""></a>
            </div>
            <div class="search-bar">
                <div class="search-form" >
                    {!! Form::open(['method' => 'get','route' => ['user.search'], 'data-parsley-validate']) !!}
                    <button type="submit" class="border-0">
                        <i class="fa fa-search"></i>
                    </button>
                        <input type="text" name="search" placeholder="Search..." list="browsers">
                        <datalist id="browsers">
                            @foreach($userprofileall as $userprofilealls)
                                <option value="{{$userprofilealls->fname}} {{$userprofilealls->lname}}">
                            @endforeach
                        </datalist>
                    {!! Form::close() !!}
                </div>
            </div>
            <nav>
                <ul>
                    <li class="small-menu-profile-pic">
                        <a href="{{route('user.home',Auth::user()->user_link)}}">
                            @if($userprofile['picture']=='yes')
                                <img id="profile_picture_check" src="{{url('/').'/public/storage/users/'.$userprofile['user_id'].'/profile_picture.jpg'}}?v={{time()}}" alt="">
                            @else
                                <img src="{{ asset('public/uploads/white.jpg') }}" alt="">
                            @endif
                            <h6>{{ (auth()->user()->name)}}</h6>
                        </a>
                    </li>
                    <li class="{{(request()->is('chat/user')) ? 'active' : ''}}">
                        <span class="count-message"></span>
                        <a href="{{route('user.chatSystem')}}">Teams</a>
                    </li>
                    <li class="{{(request()->is('/')) ? 'active' : ''}}">
                        <a href="{{route('user.news')}}" title="">Opinions</a>
                    </li>
                    
                    <li class="{{(request()->segment(1) == 'friends') ? 'active' : ''}}">
                        <a href="{{ route('user.friends',Auth::user()->user_link) }}" title="" class="not-box-openm">Friends</a>
                    </li>
                    <li class="{{(request()->is('post/all')) ? 'active' : ''}}">
                        <a href="{{ url('/post/all')}}">Specialists</a>
                    </li>
                    <li class="{{(request()->is('shop')) ? 'active' : ''}}">
                        <a href="{{route('front.shop')}}">Shop</a>
                    </li>
                    <li class="{{(request()->segment(2) == 'feedback') ? 'active' : ''}}">
                        <a href="{{route('user.feedback')}}">Feedback</a>
                    </li>

                    {{--Mobile View--}}
                    <li class="small-menu-notification-icon">
                        <a href="{{ route('user.notification.view') }}" class="not-box-open notification-link" onclick="checkedNotification()">
                            Notifications
                        </a>
                        <div class="chat-mg bx" id="count-box">
                            @if($count>0)
                                <span class="count-notification small-menu-icon">{{$count}}</span>
                            @else
                                <span class="count-notification small-menu-icon" style="display: none"></span>
                            @endif
                        </div>
                    </li>
                    <li class="small-menu-setting">
                        <a href="{{ route('user.bio') }}">Settings</a>
                    </li>
                    <li class="small-menu-logout">
                        <a href="{{ route('userlogout') }}">Logout</a>
                    </li>

                    {{--Mobile View--}}
                </ul>

            </nav>

            {{--Web View--}}
            <div class="menu-btn">
                <i class="fa fa-bars" onclick="open_menu_bar()"></i>
            </div>
            <div class="invite-friends-link invites-links-friends">
                <a style="cursor: pointer;" title="" data-toggle="modal" data-target="#invites"  onclick="via_invites()">Invite Friends</a>
            </div>
            <div class="user-account" style="margin-top: -6px;">
                <a class="user-account-info" href="{{route('user.home',Auth::user()->user_link)}}">
                    @if($userprofile['picture']=='yes')
                        <img id="profile_picture_check" src="{{url('/').'/public/storage/users/'.$userprofile['user_id'].'/profile_picture.jpg'}}?v={{time()}}" alt="">
                    @else
                        <img src="{{ asset('public/uploads/white.jpg') }}" alt="">
                    @endif
                    <h6>{{ (auth()->user()->name)}}</h6>
                </a>
                <div class="user-info">
                    <i class="fa fa-caret-down"></i>
                </div>

                <div class="notification-div">
                    <div class="chat-mg bx" id="count-box" style="position: absolute; right: 0; top: 45%;">
                        @if($count>0)
                            <span class="count-notification">{{$count}}</span>
                        @else
                            <span class="count-notification" style="display:none;"></span>
                        @endif
                        <input id="count-input" value="{{$count}}" hidden>
                    </div>

                    {{--    Notification start--}}
                    <a class="not-box-open p-2 rounded-circle notification-link notification-icon" style="cursor: pointer" onclick="checkedNotification()">
                        <img class="notification-icon" src="{{ asset('public/sports/images/login images') }}/notification.svg" alt="">
                    </a>
                    <div class="notification-box noti" id="notification">
                        <div class="nt-title">
                            <h4>Notifications</h4>
                            {{--<a href="#" title="">Mark all as read</a>--}}
                        </div>
                        <div class="nt-title">
                            <a href="{{ route('user.notification.view') }}" title="">View All Notifications</a>
                        </div>
                        <div class="nott-list" id="notification-lists">
                            @if(count($userNotifications)>0)
                                @foreach($userNotifications as $userNotification)
                                    <?php
                                    $sender=\App\Models\Admin\UserProfile::select('user_profiles.*','users.user_link as user_link')
                                        ->join('users', 'users.id', '=', 'user_profiles.user_id')->where('user_profiles.user_id',$userNotification->send_by)->first();
                                    $username = $sender['fname'].' '.$sender['lname'];
                                    $message_type=$userNotification->message_type;
                                    if($message_type=="followed")
                                    {
                                        $message = "followed you.";
                                        $url=route('user.followers',Auth::user()->user_link);
                                    }
                                    else if($message_type=="unfollowed")
                                    {
                                        $message  = "unfollowed you.";
                                        $url=route('user.followers',Auth::user()->user_link);
                                    }
                                    else if($message_type=="sentFriendRequest")
                                    {
                                        $message  = "sent you friend request.";
                                        $url=route('user.friends',['friendrequest'=>'yes','id'=>Auth::user()->user_link]);
                                    }
                                    else if($message_type=="confirmFriendRequest")
                                    {
                                        $message  = "confirmed your friend request.";
                                        $url=route('user.friends',Auth::user()->user_link);
                                    }
                                    else if($message_type=="addPost")
                                    {
                                        $message  = "added a new post.";
                                        $url=route('user.news',['random'=>$userNotification->table_id]);
                                    }
                                    else if($message_type=="joinedByInvite")
                                    {
                                        $message  = "joined Who I follow and has been added to your friend list.";
                                        $url=route('user.friends',Auth::user()->user_link);
                                    }
                                    else if($message_type=="AddedAsFriend")
                                    {
                                        $message  = "has been added to your friend list.";
                                        $url=route('user.friends',Auth::user()->user_link);
                                    }
                                    else
                                    {
                                        $message  = "";
                                        $url="";
                                    }
                                    ?>

                                <a href="{{$url}}" class="pointer-cursor" style="display: block;" onclick="readNotification({{$userNotification->id}})">
                                    @if($userNotification->read=='0')
                                        <div class="notfication-details">
                                    @else
                                        <div class="notfication-details" style="background-color: #f3f3f3">
                                    @endif

                                                    <div class="noty-user-img">

                                                        @if($sender['picture']=='yes')
                                                                <img src="{{url('/').'/public/storage/users/'.$sender['user_id'].'/profile_picture.jpg'}}?v={{time()}}" alt="">
                                                        @else
                                                                <img src="{{ asset('public/uploads/white.jpg') }}" alt="">
                                                        @endif
                                                    </div>
                                                    <div class="notification-info">
                                                        <h3>
                                                            <text style="font-weight: bold">{{$username}}</text>
                                                            <text style="font-weight: normal">{{$message}}</text>
                                                        </h3>
                                                        <p><time class="timeago" datetime="{{date("Y-m-d H:i:s", strtotime('+5 hours', strtotime($userNotification->created_at)))}}"></time></p>
                                                    </div>
                                        </div>
                                </a>
                                    @endforeach
                                @endif
                            </div>

                        </div>
                    </div>
                    {{--    Notification end--}}

                    <div class="user-account-settingss">
                        <a href="{{ route('user.bio') }}"><i class="fa fa-cog text-dark mr-4 p-2 rounded-circle"></i>Settings</a>    
                        <a href="{{ route('userlogout') }}"><i class="fa fa-sign-out text-dark mr-4 p-2 rounded-circle"></i>Logout</a>
                    </div>
                </div>
            </div>
            {{--Web View--}}

        </div>
</header>

@include('sports.js.notification')

resources/views/sports/profilephoto.blade.php
<div class="add-pic-box">
    <div class="container">
        <div class="row no-gutters">
            <div class="cover-photo">
                <button onclick="addRemoveProfilePhoto()" class="profilephoto-dropdown-open"><i class="fa fa-camera"></i></button>
                <div id="profilephoto-dropdown-content" class="add-remove-profile-photo">
                    {!! Form::model($userprofile, ['method' => 'PUT','id'=>'profilephoto', 'route' => ['user.about.update', $userprofile->id], 'data-parsley-validate' , 'files'=>'true' , 'enctype'=>'multipart/form-data']) !!}
                    <div class="upload-btn-wrappers upload-cover-photo">
                        <a class="upload-photo"><i class="fa fa-upload mr-2"></i>Upload Profile Photo</a>
                        {!! Form::file('picture', [
                            'onchange'=>'readpicURL(this,"picture")','accept'=>'image/*','id'=>'picture'
                        ]) !!}
                        @if($errors->has('picture'))
                            <span class="help-block">
                                {{ $errors->first('picture') }}
                            </span>
                        @endif
                    </div>
                    {!! Form::close() !!}
                    @if($userprofile['picture']=='yes')
                        <a class="remove-photo" onclick="removeprofilephoto()"><i class="fa fa-trash mr-2"></i>Remove Profile Photo</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@include('sports.js.cover')